[workspace]
members = ["gen"]

[package]
name = "verdi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Federico Maria Morrone <contact@morrone.dev>"]
readme = "README.md"
repository = "https://github.com/verdiwm/verdi"
publish = false

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.86"
arbitrary = { version = "1.3.2", features = ["derive"] }
bytes = { version = "1.6.0", features = ["arbitrary"] }
futures-util = { version = "0.3.30", default-features = false, features = ["sink"] }
softbuffer = { version = "0.4.4", default-features = false, features = ["wayland"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "tracing"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "tracing-log"] }
wgpu = { version = "0.20.1", default-features = false, features = ["wgsl"] }
winit = { version = "0.30.2", default-features = false, features = ["rwh_06", "wayland"] }

[patch.crates-io]
bytes = { git = "https://github.com/morr0ne/bytes", branch = "arbitrary" }
