[package]
name = "verdi"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
console-subscriber = "0.3.0"
futures = "0.3.30"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["macros", "net", "rt-multi-thread", "signal", "sync", "tracing"] }
tokio-stream = { version = "0.1.15", features = ["net"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
